= JaCaMo

:icons: font
ifdef::env-github[:outfilesuffix: .adoc]

This project aims to promote the MultiAgent Programming (MAP) approach by providing a suitable integration of tools and languages for programming the following dimensions: agents (http://jason.sf.net[Jason]), environment (http://cartago.sourceforge.net/[Cartago]), and organisation (http://moise.sf.net[Moise]).

== Documentation

Most of the JaCaMo documentation is available link:doc/readme{outfilesuffix}[in the doc folder].

== Installation


=== For JaCaMo users

Installation instructions and options for users are described link:doc/install{outfilesuffix}[here].

=== For JaCaMo developers

----
git clone https://github.com/jacamo-lang/jacamo.git
cd jacamo
./gradlew config // <1> <2>
----
<1> the config task builds the jacamo jar, configure jacamo properties file, and place all jars in `build/libs`.
<2> this task also prints out the commands to set up the `JACAMO_HOME` and `PATH` variables.

Examples can be run using the `jacamo` shell script, for example:

	jacamo examples/house-building/house.jcm

Other useful gradle tasks:

-----
gradle jar     // <1>
gradle doc     // <2>
gradle clean   // <3>
gradle release // <4>
-----
<1> generates a new jacamo jar.
<2> generates the javadoc and transforms asciidoc files into html (Docker must be running for the latter).
<3> cleans all generated files.
<4> produces a zip file in `build/distributions` to be distributed to users.

An _eclipse_ project to change the JaCaMo implementation can be created form menu "File/Import/Existing Gradle Project".

The development of the main tools used by JaCaMo is also hosted on GitHub:

- https://github.com/jason-lang/jason[Jason]
- https://github.com/CArtAgO-lang/cartago[CArtAgO]
- https://github.com/moise-lang/moise[Moise]
