= JaCaMo

:icons: font

This project aims to promote the MultiAgent Programming (MAP) approach by providing a suitable integration of tools and languages for programming the following dimensions: agents (http://jason.sf.net[Jason]), environment (http://cartago.sourceforge.net/[Cartago]), and organisation (http://moise.sf.net[Moise]).

== Installation

=== For JaCaMo users

- get a release https://sourceforge.net/projects/jacamo/files/version-0[here]
- install the eclipse plugin as described http://jacamo.sourceforge.net/eclipseplugin/tutorial[here] or configure your shell command as described http://jacamo.sourceforge.net/tutorial/hello-world/shell-based.html[here]
- follow the http://jacamo.sourceforge.net/tutorial/hello-world[Hello World tutorial]
- more documentation http://jacamo.sf.net[here]

=== For JaCaMo developers

----
git clone https://github.com/jomifred/jacamo.git
cd jacamo
gradle config // <1>
----
<1> builds the jacamo jar, configure jason properties file, and place all jars in build/libs

The config task prints out the commands to set up the JACAMO_HOME and PATH variables.

Examples can be run using the jacamo shell script, for example:

	jacamo src/examples/house-building/house.jcm

Other useful tasks:

-----
gradle jar     // <1>
gradle doc     // <2>
gradle eclipse // <3>
gradle release // <4>
-----
<1> generates a new jacamo jar
<2> generates the javadoc and transforms asciidoc files into html
<3> generates an _eclipse_ project configuration to develop JaCaMo
<4> produces a zip file to be distributed to users
