= JaCaMo

This project aims to promote the MultiAgent Programming (MAP) approach by providing a suitable integration of tools and languages for programming the following dimensions: agents (http://jason.sf.net[Jason]), environment (http://cartago.sourceforge.net/[Cartago]), and organisation (http://moise.sf.net[Moise]).

== Installation

For JaCaMo users:

- get a release https://sourceforge.net/projects/jacamo/files/version-0[here]
- install the eclipse plugin as described http://jacamo.sourceforge.net/eclipseplugin/tutorial[here]
- follow the http://jacamo.sourceforge.net/tutorial/hello-world[Hello World tutorial]
- more documentation http://jacamo.sf.net[here]

For JaCaMo developers on unix:

	git clone https://github.com/jomifred/jacamo.git
	cd jacamo
	gradle jar
	gradle config

The config task prints out the command to set up the JACAMO_HOME variable.

Examples can be run using the jacamo shell script, for example:

	scripts/jacamo src/examples/house-building/house.jcm

If you plan to use eclipse to develop JaCaMo, run the following task to create an initial project:

	gradle eclipse
