= JaCaMo

:icons: font
ifdef::env-github[:outfilesuffix: .adoc]

This project aims to promote the MultiAgent Programming (MAP) approach by providing a suitable integration of tools and languages for programming the following dimensions: agents (http://jason.sf.net[Jason]), environment (http://cartago.sourceforge.net/[Cartago]), and organisation (http://moise.sf.net[Moise]).

== Installation

=== For JaCaMo users

- get a release https://sourceforge.net/projects/jacamo/files/version-0[here]
- install the eclipse plugin as described http://jacamo.sourceforge.net/eclipseplugin/tutorial[here] or configure your shell command as described link:doc/tutorials/hello-world/shell-based{outfilesuffix}[here]
- follow the link:doc/tutorials/hello-world/readme{outfilesuffix}[Hello World tutorial]
- more documentation http://jacamo.sf.net[here]

=== For JaCaMo developers

----
git clone https://github.com/jacamo-lang/jacamo.git
cd jacamo
gradle config // <1> <2> <3>
----
<1> gradle is available https://gradle.org/gradle-download/[here].
<2> the config task builds the jacamo jar, configure jacamo properties file, and place all jars in `build/libs`.
<3> this task also prints out the commands to set up the `JACAMO_HOME` and `PATH` variables.

Examples can be run using the `jacamo` shell script, for example:

	jacamo examples/house-building/house.jcm

Other useful gradle tasks:

-----
gradle jar     // <1>
gradle doc     // <2>
gradle eclipse // <3>
gradle clean   // <4>
gradle release // <5>
-----
<1> generates a new jacamo jar.
<2> generates the javadoc and transforms asciidoc files into html (http://asciidoctor.org[asciidoctor] should be installed).
<3> generates an _eclipse_ project configuration to develop JaCaMo.
<4> cleans all generated files.
<5> produces a zip file in `build/distributions` to be distributed to users.
