= Release notes for JaCaMo

== Version 0.7

- new entries in the jcm files: `java-path` (for java sources) and `org-path` (for moise .xml files). See doc/jcm.html for more details.

- a new shell script was created to produce a single jar with all application
+
----
jacamo-jar some.jcm
----
the application then can be run by
+
----
java -jar some.jar
----
The script indeed only encapsulate the command
+
----
ant -f bin/some.xml jar
----

== Version 0.6

- New CArtAgO integration
** Use of Jason name spaces: if the focus operation is prefixed with a name space, as in `ns::focus(AID)`, all perception from AID goes to the name space `ns`. Similarly, actions, like `ns::bid(10)`, will be delivered to the artifact assigned (by focus) to name space `ns`. The annotation `artifact_id` still works and overrides the name space prefix.


** Beliefs related to CArtAgO are the following:
*** `joined(WorkspaceName,WId)`, always placed in the default name space
*** `focused(WorkspaceName,ArtName~[artifact_type(Type)]~,ArtId)`, placed in the name space where the `ArtName` is focused on.

- new versions of Moise (https://github.com/moise-lang/moise/blob/master/release-notes.adoc[0.10]), Jason (https://github.com/jason-lang/jason/blob/master/release-notes.adoc[2.0]), and Cartago (2.2).

- JaCaMo development is moved to GitHub.

- gradle is used for building the project.

== Version 0.5

- last version at source forge.
