= JaCaMo Documentation
(for JaCaMo 0.6)
:author: JaCaMo Team
:date: June 2016
:toc:right:
:source-highlighter: coderay
:coderay-linenums-mode: inline
:icons: font
:prewrap!:

== Getting Started Guides
If you’re just getting to know JaCaMo or tackling programming your first multi-agent program, these guides are for you! All you need is ??? minutes. The only prerequisites are a JDK and a text editor

== Tutorials
Designed to be completed in ??? hours, you will experience deeper, in-context explorations and practices of multi-agent oriented programming topics. After the practice of these tutorials, you will be ready to implement real-world multiagent solutions.

*  link:tutorials[JaCaMo Tutorials]

== JaCaMo FAQ

*  link:faq.adoc[JaCaMo FAQ]

== Reference Documentation
Looking for in-depth knowledge on a particular JaCaMo dimension, you will find quick access to javadoc APIs and reference documentations

*  link:jcm.adoc[JaCaMo project: jcm]
*  link:debug.adoc[Debugging in JaCaMo]
*  link:agent.adoc[Agent project: Jason]
*  link:environment.adoc[Environment project: CArTaGo]
*  link:organisation.adoc[Organisation project: Moise]
*  link:agent-env.adoc[Agent-Environment project: C4Jason]
*  link:org-env.adoc[Organisation-Environment project: ORA4MAS]
*  link:jacandroid.adoc[JaCaMo for Android]


link:documentation.adoc[Back to JaCaMo Documentation]