= JaCaMo Installation
:toc: right

We have different options to start using JaCaMo: shell script commands, Gradle, Docker, ...

The shell script option requires that you download and install JaCaMo in your machine.
Since these options do not include an IDE, you can either import the project into an Eclipse/IntelliJ/.... workspace or use some text editor (we suggest VSCode).

== GitHub codespace / GitPod

With GitHub codespace or GitPod you can develop your MAS using only a browser.

Requirements:

- A GitHub account
- A browser (Chrome and Safari works fine)

Steps for GitPod:

1. click on link:https://gitpod.io/#https://github.com/jacamo-lang/template[this link].

2. Run the MAS with the command `./gradlew run` in the terminal.

Steps for codespace:

1. Go the link:https://github.com/jacamo-lang/template[JaCaMo Template Project]

2. Click on "use this template" and then "open in a codespace":

3. Run the MAS with the command `./gradlew run` in the terminal.


== Gradle

Gradle is a very simple way to develop JaCaMo application in your machine with minimal requirements.

Requirements:

- Java >= 21

Follow the steps below to create a new application:

NOTE: The first time you run takes longer since it downloads JaCaMo.

Unix::
+
----------------
wget -q http://jacamo-lang.github.io/jacamo/nps/np1.2.zip
unzip np1.2.zip
./gradlew --console=plain
----------------

Windows::
1. Download wget -q http://jacamo-lang.github.io/jacamo/nps/np1.2.zip
2. Unzip
3. Run `gradlew.bat`

TIP: Instead of `np1.2.zip` you can use `npss.zip` to create a JaCaMo application based on the current snapshot version.

//https://curl.haxx.se[`curl`] is a program that simply downloads the `np07.zip` file from http://jacamo.sourceforge.net/nps/np07.zip.

You will be asked to enter the identification of the application and then instructions about how to run it will be shown.

Example of output:
----
> Task :run

Enter the identification of the new application: helloworld
Creating path /Users/jomi/tmp/helloworld

You can run your application with:
   cd /Users/jomi/tmp/helloworld
   ./gradlew -q --console=plain

or (if you have JaCaMo CLI installed)
   jacamo helloworld.jcm
----

If you want to run a JaCaMo application that was not created with a `build.gradle` file, you can download a template from https://raw.githubusercontent.com/jacamo-lang/jacamo/master/src/main/resources/templates/build.gradle[here] and replace

- `<VERSION>` by the required JaCaMo release (e.g. `1.0`)
- `<PROJECT-FILE>` by your .jcm file (e.g. `hello.jcm`).

To edit your code, any text editor can be used. VS Code has plugins for syntax highlight.


== JaCaMo Command Line Interface

This option requires that you install JaCaMo CLI in your machine. JaCaMo CLI has features to create and manage JaCaMo projects.

Requirements:

- Java >= 21

Download a JaCaMo release from link:https://github.com/jacamo-lang/jacamo/releases[here] (download the file named `jacamo-bin-.....zip`) and decompress it. The zip file contains documentation, examples, and a sub-directory `bin` with the file *`jacamo`*. It is a unix executable file, if not, change its properties with `chmod +x jacamo`. Finally, link:https://www.computerhope.com/issues/ch000549.htm[adds the directory `bin` in your machine `PATH`] so that the command `jacamo` can be executed in a terminal.

In a terminal, ou can create a new application named `app1` with the command

```
jacamo app create app1
```

and execute it with
```
cd app1
jacamo app1.jcm
```

Another usual option is to create an uber jar:

```
jacamo app create app2 --console
cd app2
jacamo app compile
java -jar build/libs/jacamo-app2-1.0-all.jar
```

More parameters for the `jacamo` command can be found https://github.com/jacamo-lang/jacamo-cli[here].


// [cols="<1,<1,<2",options="header"]
// |===
// | Script | Arguments | Examples
//
// | jacamo-new-project  | [_application name_]
//
//    [, `--console`]
// |  `jacamo-new-project`
//
//    `jacamo-new-project helloworld`
//
//    `jacamo-new-project helloworld --console`
//
// | jacamo              | _application name_  |  `jacamo helloworld.jcm`
//
// | jacamo-run          | _application name_  |  `jacamo-run helloworld.jcm`
//
// | jacamo-jar          | _application name_  |  `jacamo-jar helloworld.jcm`
//
// |===
//

== Docker

Requirements:

- https://www.docker.com/[Docker]

See link:https://github.com/jacamo-lang/docker[JaCaMo-Docker page] for instructions on how to create and run JaCaMo application using Docker images.
