= JaCaMo Installation
:toc: right

ifdef::env-github[:outfilesuffix: .adoc]

We have different options to start using JaCaMo: shell script commands, Gradle, Docker, ...

The shell script option requires that you download and install JaCaMo in your machine.
Since these options do not include an IDE, you can either import the project into an Eclipse/IntelliJ/.... workspace or use some text editor (we suggest VSCode).

== Gradle

Gradle is a very simple way to develop JaCaMo application in your machine with minimal requirements.

Requirements:

- Java >= 17

Follow the steps below to create a new application:

NOTE: The first time you run takes longer since it downloads JaCaMo.

Unix::
+
----------------
curl -LO http://jacamo.sourceforge.net/nps/np1.2.zip
unzip np1.2.zip
./gradlew --console=plain
----------------

Windows::
1. Download http://jacamo.sourceforge.net/nps/np1.2.zip
2. Unzip
3. Run `gradlew.bat`

TIP: Instead of `np1.2.zip` you can use `npss.zip` to create a JaCaMo application based on the current snapshot version.

//https://curl.haxx.se[`curl`] is a program that simply downloads the `np07.zip` file from http://jacamo.sourceforge.net/nps/np07.zip.

You will be asked to enter the identification of the application and then instructions about how to run it will be shown.

Example of output:
----
> Task :run

Enter the identification of the new application: helloworld
Creating path /Users/jomi/tmp/helloworld

You can run your application with:
   cd /Users/jomi/tmp/helloworld
   ./gradlew -q --console=plain

or (if you have JaCaMo CLI installed)
   jacamo helloworld.jcm
----

If you want to run a JaCaMo application that was not created with a `build.gradle` file, you can download a template from https://raw.githubusercontent.com/jacamo-lang/jacamo/master/src/main/resources/templates/build.gradle[here] and replace

- `<VERSION>` by the required JaCaMo release (e.g. `1.0`)
- `<PROJECT-FILE>` by your .jcm file (e.g. `hello.jcm`).

To edit your code, any text editor can be used. VS Code has plugins for syntax highlight.


== GitHub codespace

With GitHub codespace you can develop your MAS using only a browser.

Requirements:

- A GitHub account
- A browser (Chrome and Safari works fine)

Steps:

1. Go the link:https://github.com/jacamo-lang/template[JaCaMo Template Project]

2. Click on "use this template" and then "open in a codespace":

3. Run the MAS with the command `./gradlew run` in the terminal.


== JaCaMo Command Line Interface

This option requires that you install JaCaMo CLI in your machine. JaCaMo CLI has features to create and manage JaCaMo projects.

Requirements:

- Java >= 17



// [cols="<1,<1,<2",options="header"]
// |===
// | Script | Arguments | Examples
//
// | jacamo-new-project  | [_application name_]
//
//    [, `--console`]
// |  `jacamo-new-project`
//
//    `jacamo-new-project helloworld`
//
//    `jacamo-new-project helloworld --console`
//
// | jacamo              | _application name_  |  `jacamo helloworld.jcm`
//
// | jacamo-run          | _application name_  |  `jacamo-run helloworld.jcm`
//
// | jacamo-jar          | _application name_  |  `jacamo-jar helloworld.jcm`
//
// |===
//

== Docker

Requirements:

- https://www.docker.com/[Docker]

See link:https://github.com/jacamo-lang/docker[JaCaMo-Docker page] for instructions on how to create and run JaCaMo application using Docker images.
