= Release notes for JaCaMo

== Version 1.0

- This version uses Jason 2.6, Moise 1.0 and Cartago 3.0
- This is the version to be used with link:https://mitpress.mit.edu/books/multi-agent-oriented-programming[JaCaMo book].

== Version 0.10

- This version uses Jason 2.6, Moise 0.13 and Cartago 2.5

== Version 0.9

- This version uses Jason 2.5
- Add node red demo

== Version 0.8

- This version uses Jason 2.4, Moise 0.12 and Cartago 2.4

- Adds support for user defined *platforms*, example of projects using this feature are:
    . https://github.com/jacamo-lang/jacamo-web
    . https://github.com/jacamo-lang/camel-jason

== Version 0.7

- new entries in the jcm files: `java-path` (for java sources) and `org-path` (for moise .xml files). See doc/jcm.html for more details.

- improved installation options (gradle, docker, ...), see doc/install.html

- a new shell script was created to produce a single jar with all application
+
----
jacamo-jar some.jcm
----
the application then can be run by
+
----
java -jar some.jar
----
The script indeed only encapsulate the command
+
----
ant -f bin/some.xml jar
----

== Version 0.6

- New CArtAgO integration
** Use of Jason name spaces: if the focus operation is prefixed with a name space, as in `ns::focus(AID)`, all perception from AID goes to the name space `ns`. Similarly, actions, like `ns::bid(10)`, will be delivered to the artifact assigned (by focus) to name space `ns`. The annotation `artifact_id` still works and overrides the name space prefix.


** Beliefs related to CArtAgO are the following:
*** `joined(WorkspaceName,WId)`, always placed in the default name space
*** `focused(WorkspaceName,ArtName~[artifact_type(Type)]~,ArtId)`, placed in the name space where the `ArtName` is focused on.

- new versions of Moise (https://github.com/moise-lang/moise/blob/master/release-notes.adoc[0.10]), Jason (https://github.com/jason-lang/jason/blob/master/release-notes.adoc[2.0]), and Cartago (2.2).

- JaCaMo development is moved to GitHub.

- gradle is used for building the project.

== Version 0.5

- last version at source forge.
