#!/bin/bash

JacamoREL=0.7

if [ -z $JACAMO_HOME ] ; then
    CURDIR=`pwd`
    JACAMO_HOME=`dirname $0`
    cd "$JACAMO_HOME/.."
    JACAMO_HOME=`pwd`
    cd $CURDIR
fi

echo JaCaMo home is $JACAMO_HOME

JACAMO_JAR=$JACAMO_HOME/libs/jacamo-$JacamoREL.jar
JASON_JAR=$JACAMO_HOME/libs/JasonREL

if [ ! -f $JACAMO_JAR ] ; then
    echo JaCaMo.jar is not properly set!
    echo Value is $JACAMO_JAR
    JACAMO_JAR=`find $JACAMO_HOME/libs -name jacamo*.jar`
    JASON_JAR=`find $JACAMO_HOME/libs  -name jason*.jar`
    echo New value is $JACAMO_JAR
fi


if [ -z $JDK_HOME ] ; then
    if [ -n $JAVA_HOME ] ; then
        JDK_HOME=$JAVA_HOME
    fi
fi

# try to fix JDK_HOME on MacOS
if [ -z $JDK_HOME ] ; then
    if [ `uname` == Darwin ] ; then
           JDK_HOME=`find /Library/Java/JavaVirtualMachines -name javac | tail -1`
           JDK_HOME=`dirname $JDK_HOME`
           JDK_HOME=`dirname $JDK_HOME`
    fi
fi

# check JDK_HOME
if [ ! -f $JDK_HOME/bin/javac ] ; then
   echo JDK_HOME is not properly set!
fi
export PATH=$JDK_HOME/bin:$PATH

if [ ! -d "$HOME/.jacamo" ] ; then
    echo ----------------------------------------------------------------
    echo JaCaMo is not configured in your System
    echo run the following command to create a default configuration:
    echo       java -cp $JACAMO_JAR jacamo.util.Config
    echo ----------------------------------------------------------------
fi
