#!/bin/bash

if [ -z $JACAMO_HOME ] ; then
    CURDIR=`pwd`
    JACAMO_HOME=`dirname $0`
    cd "$JACAMO_HOME/.."
    JACAMO_HOME=`pwd`
    cd $CURDIR
fi

echo JaCaMo home is $JACAMO_HOME

if [ -z $JDK_HOME ] ; then
    if [ -n $JAVA_HOME ] ; then
	       JDK_HOME=$JAVA_HOME
    fi
fi

# try to fix JDK_HOME on MacOS
if [ -z $JDK_HOME ] ; then
    if [ `uname` == Darwin ] ; then
           JDK_HOME=`find /Library/Java/JavaVirtualMachines -name javac | tail -1`
           JDK_HOME=`dirname $JDK_HOME`
           JDK_HOME=`dirname $JDK_HOME`
       fi
fi

# check JDK_HOME
if [ ! -f $JDK_HOME/bin/javac ] ; then
   echo JDK_HOME is not properly set!
fi
export PATH=$JDK_HOME/bin:$PATH

# run jacamo application
JACAMO_JAR=`find $JACAMO_HOME/libs -name jacamo*.jar`
JASON_JAR=`find $JACAMO_HOME/libs  -name jason*.jar`

java -classpath $JACAMO_JAR:$JASON_JAR jacamo.infra.RunJaCaMoProject $1 $2
