#!/bin/sh

# this scripts transforms a moise specification (and .xml file) into
# a .dot file and then into .svg, pdf, ....

if [ -z JACAMO_HOME ] ; then
    CURDIR=`pwd`
    JACAMO_HOME=`dirname $0`
    cd "$JACAMO_HOME/.."
    JACAMO_HOME=`pwd`
    cd $CURDIR
fi

if [ -z $JDK_HOME ] ; then
    if [ -n $JAVA_HOME ] ; then
	JDK_HOME=$JAVA_HOME
    fi
fi

if [ -z $JDK_HOME ] ; then
	if [ $OS == Darwin ] ; then
		JDK_HOME=/usr
	fi
fi

# check JDK_HOME
if [ ! -f $JDK_HOME/bin/javac ] ; then
   echo JDK_HOME is not properly set!
fi

JACAMO_JAR=`find $JACAMO_HOME/libs -name jacamo*.jar`
JASON_JAR=`find $JACAMO_HOME/libs  -name jason*.jar`
MOISE_JAR=`find $JACAMO_HOME/libs  -name moise*.jar`
NPL_JAR=`find $JACAMO_HOME/libs  -name npl*.jar`
CARTAGO_JAR=`find $JACAMO_HOME/libs  -name cartago*.jar`
C4JASON_JAR=`find $JACAMO_HOME/libs  -name c4jason*.jar`

$JDK_HOME/bin/java -cp $MOISE_JAR:$JASON_JAR:$NPL_JAR:$CARTAGO_JAR:$C4JASON_JAR moise.tools.os2dot $*
